name: 'namaph_dwh'
config-version: 2
version: '0.0.1'

profile: 'namaph'

macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  namaph_dwh:
    +database: velvety-outcome-448307-f0
    +schema: mart
    master:
      +materialized: table
    forecast:
      +materialized: table
    transaction:
      +materialized: table

  elementary:
    +schema: "elementary"

seeds:
  namaph_dwh:
    +full_refresh: true
    +database: velvety-outcome-448307-f0
    +schema: master


flags:
  require_explicit_package_overrides_for_builtin_materializations: false
  source_freshness_run_project_hooks: True

