name: 'namaph_dwh'
config-version: 2
version: '0.0.1'

profile: 'namaph'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  namaph_dwh:
    +materialized: view
    +database: velvety-outcome-448307-f0
