name: 'namaph_dwh'
config-version: 2
version: '0.0.1'

profile: 'namaph'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  namaph_dwh:
    +database: velvety-outcome-448307-f0
    masters:
      +materialized: view
    forecasts:
      +materialized: view
    transactions:
      +materialized: view

  elementary:
    +schema: "elementary"


flags:
  require_explicit_package_overrides_for_builtin_materializations: false
  source_freshness_run_project_hooks: True

