services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - target: 9000
        published: 9000
      - target: 9001
        published: 9001
    volumes:
      - ./db/minio/data:/data
    environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER:-user}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
        MINIO_SERVER_URL: http://localhost:9000
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 20s
      retries: 20
      start_period: 5s

  mc:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./db/sample:/sample
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-user}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
      MINIO_ENDPOINT: http://${MINIO_ENDPOINT:-minio:9000}
    entrypoint: >
       /bin/sh -c "
        /usr/bin/mc alias set minio  $${MINIO_ENDPOINT} $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}
        if ! /usr/bin/mc ls minio/lake > /dev/null 2>&1; then
          echo Initialize the bucket
          /usr/bin/mc mb minio/lake
          /usr/bin/mc cp --recursive /sample/* minio/lake
        fi;
        exit 0;
        "
