[[Top]]
page = "modules/top/home.py"
title = "ホーム"
icon = ":material/home:"
url_path = ""
default = true

[[Top]]
page = "modules/top/dashboard.py"
title = "ダッシュボード"
icon = ":material/dashboard:"
url_path = "dashboard"

[[Data]]
page = "modules/data/overview.py"
title = "概要"
icon = ":material/function:"
url_path = "data-overview"

[[Data]]
page = "modules/data/axis.py"
title = "属性設定"
icon = ":material/function:"
url_path = "axis"

[[Data]]
page = "modules/data/vsforecast.py"
title = "予測/実績"
icon = ":material/function:"
url_path = "vsforecast"

[[Planning]]
page = "modules/planning/sales.py"
title = "販売計画"
icon = ":material/edit:"
url_path = "sales-plan"

[[Planning]]
page = "modules/planning/proration.py"
title = "調達計画"
icon = ":material/edit:"
url_path = "proration-plan"

[[Planning]]
page = "modules/planning/supply.py"
title = "供給計画"
icon = ":material/edit:"
url_path = "supply-plan"

[[EventSupport]]
page = "modules/top/contingency_plan.py"
title = "緊急計画"
icon = ":material/dashboard:"
url_path = "contingency-plan"
