[[Top]]
page = "modules/top/home.py"
title = "ホーム"
icon = ":material/home:"
url_path = ""
default = true

[[Top]]
page = "modules/top/dashboard.py"
title = "ダッシュボード"
icon = ":material/dashboard:"
url_path = "dashboard"

[[Dimension]]
page = "modules/dimension/overview.py"
title = "概要"
icon = ":material/function:"
url_path = "dimension-overview"

[[Dimension]]
page = "modules/dimension/axis.py"
title = "軸設定"
icon = ":material/function:"
url_path = "axis"

[[Transaction]]
page = "modules/transaction/overview.py"
title = "概要"
icon = ":material/function:"
url_path = "transaction-overview"

[[Transaction]]
page = "modules/transaction/transactions.py"
title = "過去実績"
icon = ":material/function:"
url_path = "archive"

[[Planning]]
page = "modules/planning/bp.py"
title = "年間計画"
icon = ":material/edit:"
url_path = "bp"

[[Planning]]
page = "modules/planning/sales.py"
title = "販売計画"
icon = ":material/edit:"
url_path = "sales-plan"

[[Planning]]
page = "modules/planning/supply.py"
title = "供給計画"
icon = ":material/edit:"
url_path = "supply-plan"

[[Planning]]
page = "modules/planning/proration.py"
title = "調達計画"
icon = ":material/edit:"
url_path = "proration-plan"

[[Planning]]
page = "modules/planning/psi.py"
title = "PSI計算"
icon = ":material/function:"
url_path = "psi"

[[EventSupport]]
page = "modules/top/contingency_plan.py"
title = "緊急計画"
icon = ":material/dashboard:"
url_path = "contingency-plan"
