from vertexai.generative_models import GenerationConfig, Part

system_instruction = """
You are a data analyst.
BQからの結果を元に、データの解釈を日本語で記述してください。
マスタデータはTablesのスキームに従って作られています。
アウトプットの形式の中に下記を含んでください。
- "interpretation": {"type": "string"}
    データの解釈を文字で書いてください。
- "plot_type": {"type": "string"}
    データをplotlyでプロットする際のプロット方式("bar"または"line")を記載してください。
- "x_axis": {"type": "string"}
    x軸に設定するべき属性を記載してください。
- "y_axis": {"type": "string"}
    y軸に設定するべき属性を記載してください。
===Tables
{"kind":"bigquery#table","etag":"c2h/Ger3g4ADuA2sk8F7WA==","id":"velvety-outcome-448307-f0:master_data.bom_trees","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/bom_trees","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"bom_trees"},"schema":{"fields":[{"name":"parent_item_code","type":"STRING","mode":"NULLABLE"},{"name":"child_item_code","type":"STRING","mode":"NULLABLE"},{"name":"quantity","type":"INTEGER","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"105","numLongTermBytes":"0","numRows":"5","creationTime":"1737911020629","lastModifiedTime":"1737912629753","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"4980","numTotalLogicalBytes":"105","numActiveLogicalBytes":"105","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"6640","numActivePhysicalBytes":"6640","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1660"}
{"kind":"bigquery#table","etag":"BKGHOGCFPwqB0oDvV5vEhQ==","id":"velvety-outcome-448307-f0:master_data.companies","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/companies","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"companies"},"schema":{"fields":[{"name":"company_code","type":"STRING","mode":"NULLABLE"},{"name":"company_name","type":"STRING","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"22","numLongTermBytes":"0","numRows":"1","creationTime":"1737910980463","lastModifiedTime":"1737912589537","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"4207","numTotalLogicalBytes":"22","numActiveLogicalBytes":"22","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"5609","numActivePhysicalBytes":"5609","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1402"}
{"kind":"bigquery#table","etag":"fuQQu6Yw53oVZ2Orna1Gog==","id":"velvety-outcome-448307-f0:master_data.customers","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/customers","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"customers"},"schema":{"fields":[{"name":"customer_code","type":"STRING","mode":"NULLABLE"},{"name":"customer_name","type":"STRING","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"120","numLongTermBytes":"0","numRows":"6","creationTime":"1737910983672","lastModifiedTime":"1737912593455","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"4368","numTotalLogicalBytes":"120","numActiveLogicalBytes":"120","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"5825","numActivePhysicalBytes":"5825","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1457"}
{"kind":"bigquery#table","etag":"I8gXzjtbz8ejP2cTr6QSWA==","id":"velvety-outcome-448307-f0:master_data.dates","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/dates","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"dates"},"schema":{"fields":[{"name":"date_code","type":"INTEGER","mode":"NULLABLE"},{"name":"date_name","type":"STRING","mode":"NULLABLE"},{"name":"month_code","type":"INTEGER","mode":"NULLABLE"}]},"numBytes":"7922","numLongTermBytes":"0","numRows":"365","creationTime":"1737911008673","lastModifiedTime":"1737912618548","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"5455","numTotalLogicalBytes":"7922","numActiveLogicalBytes":"7922","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"7273","numActivePhysicalBytes":"7273","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1818"}
{"kind":"bigquery#table","etag":"/t3/Je7lhhQwOyCMF+Hu4w==","id":"velvety-outcome-448307-f0:master_data.finished_goods","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/finished_goods","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"finished_goods"},"schema":{"fields":[{"name":"finished_goods_code","type":"STRING","mode":"NULLABLE"},{"name":"finished_goods_name","type":"STRING","mode":"NULLABLE"},{"name":"item_code","type":"STRING","mode":"NULLABLE"},{"name":"item_type_code","type":"STRING","mode":"NULLABLE"},{"name":"finished_goods_volume","type":"FLOAT","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"73","numLongTermBytes":"0","numRows":"2","creationTime":"1737910966557","lastModifiedTime":"1737912577434","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"6361","numTotalLogicalBytes":"73","numActiveLogicalBytes":"73","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"8481","numActivePhysicalBytes":"8481","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"2120"}
{"kind":"bigquery#table","etag":"VWb8WU2SlOlbzoEt0Zbivw==","id":"velvety-outcome-448307-f0:master_data.item_types","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/item_types","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"item_types"},"schema":{"fields":[{"name":"item_type_code","type":"STRING","mode":"NULLABLE"},{"name":"item_type_name","type":"STRING","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"40","numLongTermBytes":"0","numRows":"2","creationTime":"1737910973521","lastModifiedTime":"1737912583267","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"4331","numTotalLogicalBytes":"40","numActiveLogicalBytes":"40","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"5775","numActivePhysicalBytes":"5775","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1444"}
{"kind":"bigquery#table","etag":"sJDIH+Cmallecp+WQn7iug==","id":"velvety-outcome-448307-f0:master_data.items","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/items","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"items"},"schema":{"fields":[{"name":"item_code","type":"STRING","mode":"NULLABLE"},{"name":"resource_code","type":"STRING","mode":"NULLABLE"},{"name":"item_type","type":"STRING","mode":"NULLABLE"},{"name":"item_name","type":"STRING","mode":"NULLABLE"},{"name":"item_volume","type":"FLOAT","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"252","numLongTermBytes":"0","numRows":"7","creationTime":"1737910977493","lastModifiedTime":"1737973117410","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"6693","numTotalLogicalBytes":"252","numActiveLogicalBytes":"252","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"10345","numActivePhysicalBytes":"10345","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"3652"}
{"kind":"bigquery#table","etag":"gHIancKQYxtBf4Zkxp0HUg==","id":"velvety-outcome-448307-f0:master_data.lines","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/lines","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"lines"},"schema":{"fields":[{"name":"line_code","type":"STRING","mode":"NULLABLE"},{"name":"line_name","type":"STRING","mode":"NULLABLE"},{"name":"plant_code","type":"STRING","mode":"NULLABLE"},{"name":"month","type":"INTEGER","mode":"NULLABLE"},{"name":"capacity","type":"INTEGER","mode":"NULLABLE"},{"name":"production_cost","type":"INTEGER","mode":"NULLABLE"}]},"numBytes":"1104","numLongTermBytes":"0","numRows":"24","creationTime":"1737910997021","lastModifiedTime":"1737912608061","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"6463","numTotalLogicalBytes":"1104","numActiveLogicalBytes":"1104","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"8617","numActivePhysicalBytes":"8617","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"2154"}
{"kind":"bigquery#table","etag":"S388N0V9mjE+7B+eBESDIQ==","id":"velvety-outcome-448307-f0:master_data.locations","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/locations","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"locations"},"schema":{"fields":[{"name":"location_code","type":"STRING","mode":"NULLABLE"},{"name":"location_name","type":"STRING","mode":"NULLABLE"},{"name":"longuitude","type":"FLOAT","mode":"NULLABLE"},{"name":"latitude","type":"FLOAT","mode":"NULLABLE"}]},"numBytes":"250","numLongTermBytes":"0","numRows":"8","creationTime":"1737910990115","lastModifiedTime":"1737912602169","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"5645","numTotalLogicalBytes":"250","numActiveLogicalBytes":"250","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"7526","numActivePhysicalBytes":"7526","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1881"}
{"kind":"bigquery#table","etag":"7cGYp1e77CjW3Xwa6eo/WA==","id":"velvety-outcome-448307-f0:master_data.materials","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/materials","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"materials"},"schema":{"fields":[{"name":"material_code","type":"STRING","mode":"NULLABLE"},{"name":"material_name","type":"STRING","mode":"NULLABLE"},{"name":"item_code","type":"STRING","mode":"NULLABLE"},{"name":"item_type_code","type":"STRING","mode":"NULLABLE"},{"name":"materials_volume","type":"FLOAT","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"159","numLongTermBytes":"0","numRows":"4","creationTime":"1737910969550","lastModifiedTime":"1737912580242","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"6538","numTotalLogicalBytes":"159","numActiveLogicalBytes":"159","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"8717","numActivePhysicalBytes":"8717","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"2179"}
{"kind":"bigquery#table","etag":"XyEgFsGKEUxUTXZP4ntQKw==","id":"velvety-outcome-448307-f0:master_data.months","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/months","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"months"},"schema":{"fields":[{"name":"month_code","type":"INTEGER","mode":"NULLABLE"},{"name":"month_name","type":"STRING","mode":"NULLABLE"},{"name":"year_code","type":"INTEGER","mode":"NULLABLE"}]},"numBytes":"290","numLongTermBytes":"0","numRows":"12","creationTime":"1737911004996","lastModifiedTime":"1737912615505","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"4644","numTotalLogicalBytes":"290","numActiveLogicalBytes":"290","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"6191","numActivePhysicalBytes":"6191","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1547"}
{"kind":"bigquery#table","etag":"B/aXfhiZeIrP0aD+B4O+/Q==","id":"velvety-outcome-448307-f0:master_data.plants","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/plants","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"plants"},"schema":{"fields":[{"name":"plant_code","type":"STRING","mode":"NULLABLE"},{"name":"plant_name","type":"STRING","mode":"NULLABLE"},{"name":"location_code","type":"STRING","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"218","numLongTermBytes":"0","numRows":"8","creationTime":"1737910987320","lastModifiedTime":"1737912599119","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"5319","numTotalLogicalBytes":"218","numActiveLogicalBytes":"218","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"7091","numActivePhysicalBytes":"7091","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1772"}
{"kind":"bigquery#table","etag":"7KFrAT84xqcvTrmFQ17kww==","id":"velvety-outcome-448307-f0:master_data.production_forecasts","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/production_forecasts","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"production_forecasts"},"schema":{"fields":[{"name":"line_code","type":"STRING","mode":"NULLABLE"},{"name":"item_code","type":"STRING","mode":"NULLABLE"},{"name":"versions_code","type":"STRING","mode":"NULLABLE"},{"name":"month","type":"INTEGER","mode":"NULLABLE"},{"name":"quantity","type":"INTEGER","mode":"NULLABLE"}]},"numBytes":"1632","numLongTermBytes":"0","numRows":"48","creationTime":"1737911026562","lastModifiedTime":"1737912635886","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"6266","numTotalLogicalBytes":"1632","numActiveLogicalBytes":"1632","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"8354","numActivePhysicalBytes":"8354","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"2088"}
{"kind":"bigquery#table","etag":"j2GmRYPYiMg5aQWLsejryw==","id":"velvety-outcome-448307-f0:master_data.resource_forecasts","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/resource_forecasts","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"resource_forecasts"},"schema":{"fields":[{"name":"customer_code","type":"STRING","mode":"NULLABLE"},{"name":"item_code","type":"STRING","mode":"NULLABLE"},{"name":"versions_code","type":"STRING","mode":"NULLABLE"},{"name":"month","type":"INTEGER","mode":"NULLABLE"},{"name":"capacity","type":"INTEGER","mode":"NULLABLE"}]},"numBytes":"4896","numLongTermBytes":"0","numRows":"144","creationTime":"1737911031206","lastModifiedTime":"1737912640491","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"5968","numTotalLogicalBytes":"4896","numActiveLogicalBytes":"4896","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"7957","numActivePhysicalBytes":"7957","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1989"}
{"kind":"bigquery#table","etag":"VE9h5PHxDeP32yqwqZReMg==","id":"velvety-outcome-448307-f0:master_data.retailers","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/retailers","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"retailers"},"schema":{"fields":[{"name":"retailer_code","type":"STRING","mode":"NULLABLE"},{"name":"retailer_name","type":"STRING","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"60","numLongTermBytes":"0","numRows":"3","creationTime":"1737911035232","lastModifiedTime":"1737912645702","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"4297","numTotalLogicalBytes":"60","numActiveLogicalBytes":"60","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"5729","numActivePhysicalBytes":"5729","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1432"}
{"kind":"bigquery#table","etag":"CEJfn5QeDgecQDNNM+J9Jg==","id":"velvety-outcome-448307-f0:master_data.sales_forecasts","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/sales_forecasts","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"sales_forecasts"},"schema":{"fields":[{"name":"company_code","type":"STRING","mode":"NULLABLE"},{"name":"customer_code","type":"STRING","mode":"NULLABLE"},{"name":"item_code","type":"STRING","mode":"NULLABLE"},{"name":"versions_code","type":"STRING","mode":"NULLABLE"},{"name":"date","type":"DATE","mode":"NULLABLE"},{"name":"quantity","type":"INTEGER","mode":"NULLABLE"}]},"numBytes":"2952","numLongTermBytes":"0","numRows":"72","creationTime":"1737911023768","lastModifiedTime":"1737912632986","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"6668","numTotalLogicalBytes":"2952","numActiveLogicalBytes":"2952","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"8890","numActivePhysicalBytes":"8890","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"2222"}
{"kind":"bigquery#table","etag":"lWweP5+YtqbgFCW3KOo7tw==","id":"velvety-outcome-448307-f0:master_data.storages","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/storages","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"storages"},"schema":{"fields":[{"name":"storage_code","type":"STRING","mode":"NULLABLE"},{"name":"storage_name","type":"STRING","mode":"NULLABLE"},{"name":"plant_code","type":"STRING","mode":"NULLABLE"},{"name":"month","type":"INTEGER","mode":"NULLABLE"},{"name":"item_code","type":"STRING","mode":"NULLABLE"},{"name":"target_quantity","type":"INTEGER","mode":"NULLABLE"},{"name":"storage_unit_cost","type":"INTEGER","mode":"NULLABLE"}]},"numBytes":"13968","numLongTermBytes":"0","numRows":"264","creationTime":"1737910993904","lastModifiedTime":"1737912605381","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"8184","numTotalLogicalBytes":"13968","numActiveLogicalBytes":"13968","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"10911","numActivePhysicalBytes":"10911","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"2727"}
{"kind":"bigquery#table","etag":"C3lPzIhu2B8K/ZelBVFtaA==","id":"velvety-outcome-448307-f0:master_data.suppliers","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/suppliers","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"suppliers"},"schema":{"fields":[{"name":"supplier_code","type":"STRING","mode":"NULLABLE"},{"name":"supplier_name","type":"STRING","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"60","numLongTermBytes":"0","numRows":"3","creationTime":"1737911039333","lastModifiedTime":"1737912648678","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"4291","numTotalLogicalBytes":"60","numActiveLogicalBytes":"60","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"5721","numActivePhysicalBytes":"5721","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1430"}
{"kind":"bigquery#table","etag":"sy21TV0IqtDEJKBkWqpngg==","id":"velvety-outcome-448307-f0:master_data.times","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/times","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"times"},"schema":{"fields":[{"name":"time_id","type":"DATE","mode":"NULLABLE"},{"name":"year_code","type":"INTEGER","mode":"NULLABLE"},{"name":"year_name","type":"INTEGER","mode":"NULLABLE"},{"name":"month_code","type":"INTEGER","mode":"NULLABLE"},{"name":"month_name","type":"STRING","mode":"NULLABLE"},{"name":"date_code","type":"INTEGER","mode":"NULLABLE"},{"name":"date_name","type":"STRING","mode":"NULLABLE"}]},"numBytes":"19656","numLongTermBytes":"0","numRows":"365","creationTime":"1737911042933","lastModifiedTime":"1737912651343","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"9449","numTotalLogicalBytes":"19656","numActiveLogicalBytes":"19656","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"12599","numActivePhysicalBytes":"12599","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"3150"}
{"kind":"bigquery#table","etag":"4zf9+/PvRrwa1fiTtdjMQA==","id":"velvety-outcome-448307-f0:master_data.transaction_types","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/transaction_types","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"transaction_types"},"schema":{"fields":[{"name":"transaction_type_code","type":"STRING","mode":"NULLABLE"},{"name":"transaction_type_name","type":"STRING","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"33","numLongTermBytes":"0","numRows":"2","creationTime":"1737911016768","lastModifiedTime":"1737912626264","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"4317","numTotalLogicalBytes":"33","numActiveLogicalBytes":"33","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"5755","numActivePhysicalBytes":"5755","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1438"}
{"kind":"bigquery#table","etag":"o6L4oaW0NMDfsdjij+wEMg==","id":"velvety-outcome-448307-f0:master_data.transactions","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/transactions","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"transactions"},"schema":{"fields":[{"name":"company_code","type":"STRING","mode":"NULLABLE"},{"name":"customer_code","type":"STRING","mode":"NULLABLE"},{"name":"month","type":"INTEGER","mode":"NULLABLE"},{"name":"item_code","type":"STRING","mode":"NULLABLE"},{"name":"transaction_type","type":"STRING","mode":"NULLABLE"},{"name":"storage_code","type":"STRING","mode":"NULLABLE"},{"name":"price","type":"INTEGER","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"10584","numLongTermBytes":"0","numRows":"216","creationTime":"1737911012105","lastModifiedTime":"1737912623430","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"8431","numTotalLogicalBytes":"10584","numActiveLogicalBytes":"10584","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"11241","numActivePhysicalBytes":"11241","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"2810"}
{"kind":"bigquery#table","etag":"ng+ldLNLO92nFb4/1i+CIg==","id":"velvety-outcome-448307-f0:master_data.versions","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/versions","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"versions"},"schema":{"fields":[{"name":"versions_code","type":"STRING","mode":"NULLABLE"},{"name":"versions_name","type":"STRING","mode":"NULLABLE"},{"name":"is_active","type":"BOOLEAN","mode":"NULLABLE"}]},"numBytes":"80","numLongTermBytes":"0","numRows":"4","creationTime":"1737911046082","lastModifiedTime":"1737912654518","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"4413","numTotalLogicalBytes":"80","numActiveLogicalBytes":"80","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"5884","numActivePhysicalBytes":"5884","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"1471"}
{"kind":"bigquery#table","etag":"L529zG1ot+nL+oqIl0GGmQ==","id":"velvety-outcome-448307-f0:master_data.years","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/velvety-outcome-448307-f0/datasets/master_data/tables/years","tableReference":{"projectId":"velvety-outcome-448307-f0","datasetId":"master_data","tableId":"years"},"schema":{"fields":[{"name":"year_code","type":"INTEGER","mode":"NULLABLE"},{"name":"year_name","type":"INTEGER","mode":"NULLABLE"}]},"numBytes":"16","numLongTermBytes":"0","numRows":"1","creationTime":"1737911000343","lastModifiedTime":"1737912611717","type":"TABLE","location":"us-west1","numTimeTravelPhysicalBytes":"2858","numTotalLogicalBytes":"16","numActiveLogicalBytes":"16","numLongTermLogicalBytes":"0","numTotalPhysicalBytes":"3811","numActivePhysicalBytes":"3811","numLongTermPhysicalBytes":"0","numCurrentPhysicalBytes":"953"}
Data: """

interpreter_conf = dict(
    model_name="gemini-1.5-flash",
    generation_config=GenerationConfig(
        temperature=1,
        top_p=0.95,
        max_output_tokens=8192,
        response_modalities=["TEXT"],
        response_mime_type="application/json",
        response_schema={
            "type": "object",
            "properties": {
                "interpretation": {"type": "string"},
                "plot_type": {"type": "string"},
                "x_axis": {"type": "string"},
                "y_axis": {"type": "string"},
            },
            "required": ["interpretation", "plot_type"],
        },
    ),
    system_instruction=[Part.from_text(system_instruction)],
)
